swagger: "2.0"

info:
  title: "{{title}}"
  version: "1.0"

basePath: /swagger

paths:
  /greeting/{name}:
    post:
      summary: Generate greeting
      description: Generates a greeting message.
      operationId: hello.post_greeting
      produces:
        - text/plain;
      responses:
        '200':
          description: greeting response
          schema:
            type: string
          examples:
            "text/plain": "Hello John"
      parameters:
        - name: name
          in: path
          description: Name of the person to greet.
          required: true
          type: string
