swagger: "2.0"
info:
  title: Basic Auth Example
  version: "1.0"
basePath: /swagger
paths:
  /secret:
    get:
      summary: Return secret string
      operationId: app.get_secret
      responses:
        '200':
          description: secret response
          schema:
            type: string
      security:
        - basic: []
securityDefinitions:
  basic:
    type: basic
    x-basicInfoFunc: app.basic_auth
